apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-jordan
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-jordan
  template:
    metadata:
      labels:
        app: treasure-jordan
    spec:
      containers:
        - name: web
          image: durasnoxs/tesoro-jordan:latest
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasure Hunt — Jordan"
            - name: STUDENT
              value: "jordan"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "a08b6d82c584569425480baeef55afee066fe7b9267d3c7edab65a3cdbc4dda4"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: jordan-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-jordan
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-jordan
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
